# This is a initial setup enmviroment. 
# You can delete this file once executed in your repository 

name: create-env-repo

on:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  trigger_env:
   uses: Blue-Express/blue-sbx-templates/.github/workflows/sync-env-repo.yaml@blue
   secrets:
     API_TOKEN_GITHUB: inherit

  wait:
   runs-on: ubuntu-latest
   needs: trigger_env
   steps:
     - name: Wait for 3 seconds
       run: sleep 3

  sync_secrets:
    runs-on: ubuntu-latest
    needs: wait
    env:
      TARGET_REPO: 'blue-sbx-templates'
    strategy:
      matrix:
        config:
          - environment: 'dev'
            ref: 'blue'
            dry_run: 'false'
          - environment: 'qa'
            ref: 'blue'
            dry_run: 'false'
          - environment: 'prod'
            ref: 'blue'
            dry_run: 'false'
    steps:
      - name: Trigger secrets-sync-back workflow
        run: |
          owner=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)

          curl -XPOST -H "Authorization: token ${{ secrets.PERSONAL_GITHUB_TOKEN_CLASSIC }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/$owner/$TARGET_REPO/actions/workflows/sync-secrets-back.yaml/dispatches \
            -d '{"ref": "${{ matrix.config.ref }}", "inputs": {"environment": "${{ matrix.config.environment }}", "reponame": "'$GITHUB_REPOSITORY'", "dry_run": "${{ matrix.config.dry_run }}"}}'